// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clflvxrdvihashuqzody.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZmx2eHJkdmloYXNodXF6b2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTEzNzQsImV4cCI6MjA1MDI4NzM3NH0.XbW0LYtYZWcy59ZiP16ziEtKDoQ7VDlGLrTg0qlZBFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);